export const LOGO = "/asset/images/logo.png"
export const LOGOBIG = "/asset/images/logo.png"
export const Header1 = "/asset/images/header1.png"
export const Header2 = "/asset/images/header2.png"
export const homehead = "/asset/images/homeheader.png"
export const LOGIN = "/asset/images/login.png"
export const REGIS = "/asset/images/regis.png"
